### PR TITLE
Fix 717 autopublish via nexus without manual steps

### LINKED ISSUE #717: Automate Nexus publishing
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

There should be no manual action required to push artifacts to maven central; it should be automated from a tag. Currently Nexus OSSRH requires manual steps.

This seems to be a promising Gradle plugin solving this particular problem:

https://github.com/gradle-nexus/publish-plugin/

Also fixup the default gradle files created by pulumi-java-gen to take advantage of this.

### PR DESCRIPTION
**Pull request by t0yv0**
# Description

Fixes #717  - gradle can now fully publish to Maven Central without any manual steps.

1. Fix the Java SDK in this repo to use io.github.gradle-nexus.publish-plugin

2. Add options to generate build.gradle in pulumi-java-gen to use io.github.gradle-nexus.publish-plugin

Test script for publishing the SDK:

```
#!/usr/bin/env bash

set -euo pipefail

export PULUMI_JAVA_SDK_VERSION=$(pulumictl get version --tag-pattern '^sdk')

export OSSRH_USERNAME=$(pass issues.sonatype.org/user-token-for-t0yv0/username)
export OSSRH_PASSWORD=$(pass issues.sonatype.org/user-token-for-t0yv0/password)

export SIGNING_KEY=$(cat ~/tmp/support-at-pulumi-dot-com.secret)
# export SIGNING_KEY_ID=0xBE76937 92EC8 7BB8
export SIGNING_KEY_ID=2EC87BB8
export SIGNING_PASSWORD=$(pass gpg/support@pulumi.com/passphrase)

echo "Publishing $PULUMI_JAVA_SDK_VERSION"

(cd sdk/java && gradle pulumi:publishToSonatype closeAndReleaseSonatypeStagingRepository --stacktrace)
```

Test script for publishing a provider generated by pulumi-java-gen:

```
#!/usr/bin/env bash

set -euo pipefail

export SIGNING_KEY=$(cat ~/tmp/support-at-pulumi-dot-com.secret)
# export SIGNING_KEY_ID=0xBE76937 92EC8 7BB8
export SIGNING_KEY_ID=2EC87BB8
export SIGNING_PASSWORD=$(pass gpg/support@pulumi.com/passphrase)
export PUBLISH_REPO_USERNAME=$(pass issues.sonatype.org/user-token-for-t0yv0/username)
export PUBLISH_REPO_PASSWORD=$(pass issues.sonatype.org/user-token-for-t0yv0/password)
export PACKAGE_VERSION=$(pulumictl get version --tag-pattern "^random")

rm -rf bin/pulumi-java-gen
make bin/pulumi-java-gen

rm -rf gen

./bin/pulumi-java-gen \
    generate \
    --schema https://raw.githubusercontent.com/pulumi/pulumi-random/v4.6.0/provider/cmd/pulumi-resource-random/schema.json \
    --sdk 0.4.1 \
    --override overrides.json \
    --out gen

echo "Publishing $PACKAGE_VERSION"
(cd gen && gradle publishToSonatype closeAndReleaseSonatypeStagingRepository --stacktrace)
```

Note:

```
$ cat overrides.json   
{
    "buildFiles": "gradle",
    "gradleNexusPublishPluginVersion": "1.1.0"
}
```

I've obtained at least https://s01.oss.sonatype.org/content/groups/public/com/pulumi/random/4.7.0-alpha.1657304919+1d411918/ from the second test script, it seems to work.

Can consider adding a CLI option to short-cut the overrides.json dance.

## Checklist

- [ ] I have added tests that prove my fix is effective or that my feature works

- [ ] I have updated the [CHANGELOG-PENDING](https://github.com/pulumi/pulumi/blob/master/CHANGELOG_PENDING.md) file with my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Service API version

### CODE REVIEW

**Comment by t0yv0** [comment]
Comment from @stack72 - need to make this behavior default.

**Comment by t0yv0** [comment]
@stack72 how about this. You can now pass `--build gradle-nexus` to opt into this behavior. The default is still `--build gradle`.

```
./bin/pulumi-java-gen \
    generate \
    --schema https://raw.githubusercontent.com/pulumi/pulumi-random/v4.6.0/provider/cmd/pulumi-resource-random/schema.json \
    --sdk 0.4.1 \
    --build gradle-nexus \
    --out gen
```

**Comment by t0yv0** [comment]
Will need https://github.com/pulumi/pulumi-java/pull/738 first and re-check that publishToSonatype respects generating those missing resources.

**Review by dixler — APPROVED** [review]
lgtm

**Pull request merged**
