### PR TITLE
Fix google native provider packages

### LINKED ISSUE #381: Fix generated package and class names for versioned APIs
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Currently when generating providers we don't handle versioned APIs very well (kubernetes, google-native, others?).

Expectations:
- `io.pulumi.googlenative.accesscontextmanager_v1` -> `io.pulumi.googlenative.accesscontextmanager.v1`
- `Accesscontextmanager_v1Functions ` -> `AccesscontextmanagerFunctions`

I've seen this mechanism used to correct this type of provider specific problems:
https://github.com/VirtusLab/pulumi-kubernetes/commit/2e08c5e7ded01eee32832f9fbfefadad9a2a375c#diff-8dfd74ae4dfdfd04f5c226c8e65a2d3060d6761b45252ba7a757c22492d99311R42460

Underscores in packages should only be used to escape reserved keywords and when the name starts with a number, e.g.:
- `org.example.foo.class_.for_.void_`
- `org/example.bar._23games`

### PR DESCRIPTION
**Pull request by pawelprazak**
# Description

Fixes #381 

## Checklist

- [ ] I have added tests that prove my fix is effective or that my feature works

- [x] I have updated the [CHANGELOG-PENDING](https://github.com/pulumi/pulumi/blob/master/CHANGELOG_PENDING.md) file with my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Service API version

### CODE REVIEW

**Comment by pawelprazak** [comment]
missing codegen, until I figure out how to update the shema in the upstream repo

**Comment by t0yv0** [comment]
Why is the dirty check failing? I fear the google-native generated code is not up to date, and the example hasn't been fixed up.

**Comment by t0yv0** [comment]
>  TBH I'm not sure, maybe I should use the 0.18.2 instead of updating to latest

For this check it versions don't matter, it just means maybe you did not run `make provider.gcp.generate`? Let me check it out and try.

**Comment by pawelprazak** [comment]
merged the missing codegen, rebased on master

**Review by t0yv0 — APPROVED** [review]

**Comment by t0yv0** [comment]
LGTM if tests pass ok to merge.

**Comment by pawelprazak** [comment]
thank you, ideally upstream PR would be merged before this one:
https://github.com/pulumi/pulumi-google-native/pull/554

**Comment by pawelprazak** [comment]
rebased

**Comment by t0yv0** [comment]
LGTM let's merge up.

**Pull request merged**
