### PR TITLE
Bump default pulumi sdk version

### PR DESCRIPTION
**Pull request by t0yv0**
# Description

Fixes # (issue)

## Checklist

- [ ] I have added tests that prove my fix is effective or that my feature works

- [ ] I have updated the [CHANGELOG-PENDING](https://github.com/pulumi/pulumi/blob/master/CHANGELOG_PENDING.md) file with my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Service API version

### CODE REVIEW

**Comment by t0yv0** [comment]
Having some difficulty with flaky CI but I think we should do this as a pre-req to pubishing new providers.

**Review by pawelprazak — APPROVED** [review]

**Comment by pawelprazak** [comment]
apropos bumping versions, we should bump grpc/guava/gson and other deps

**Comment by t0yv0** [comment]
> apropos bumping versions, we should bump grpc/guava/gson and other deps

Very true, we need some kind of process/reminder to regularly do that, regular maintenance.

For this particular one, we should automate it, it is annoying to do.

**Comment by pawelprazak** [comment]
> > apropos bumping versions, we should bump grpc/guava/gson and other deps
> 
> Very true, we need some kind of process/reminder to regularly do that, regular maintenance.
> 
> For this particular one, we should automate it, it is annoying to do.

looks like an option: https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions

**Pull request merged**
