### PR TITLE
Fix import path for provider resources on `pulumi convert`

### PR DESCRIPTION
**Pull request by aq17**
# Description

Fixes `pu/pu` [#283](https://github.com/pulumi/pulumi-yaml/issues/283) for Java

## Checklist

- [ ] I have added tests that prove my fix is effective or that my feature works

- [x] I have updated the [CHANGELOG-PENDING](https://github.com/pulumi/pulumi/blob/master/CHANGELOG_PENDING.md) file with my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Service API version

### CODE REVIEW

**Comment by aq17** [comment]
@Zaid-Ajaj @t0yv0 I'm having trouble testing this ([Levi's comment with current invalid output](https://github.com/pulumi/pulumi/pull/10150)) due to [#702](https://github.com/pulumi/pulumi-java/issues/702) still open

**Comment by t0yv0** [comment]
We should fix that. Can mark current one as blocked for now, pointing to
the blocker.

**Comment by myhau** [comment]
@t0yv0 @aq17 I've opened a draft PR with the fix for #702 here: https://github.com/pulumi/pulumi-java/pull/773. I need some early feedback before finishing up the work (see questions and todo sections in the PR description).

**Comment by t0yv0** [comment]
This should be unblocked now @aq17 🙂 

Could we add a quick test?

**Review by AaronFriel — COMMENTED** [review]
It might be simpler to remove the special casing in this PR, and use the `pcl.MapProvidersAsResources` trick, which simplifies codegen by removing a number of special cases. It remaps the token `pulumi:providers:foo` to `foo::Provider`, which enables existing codegen to work without special casing providers:

https://github.com/pulumi/pulumi/blob/4b6d3521407764305ca46dc18d06707930e318e1/pkg/codegen/pcl/utilities.go#L139-L144

In Python, C#, TS, and Go codegen, we call that at the beginning of GenerateProgram like so:

https://github.com/pulumi/pulumi/blob/4b6d3521407764305ca46dc18d06707930e318e1/pkg/codegen/go/gen_program.go#L56-L59

**Comment by AaronFriel** [comment]
Much smaller diff! 🎉

**Review by Zaid-Ajaj — APPROVED** [review]
Looks great!

**Comment by t0yv0** [comment]
Merging, thanks team! :shipit:

**Pull request merged**
