### PR TITLE
add support for api gateway

### PR DESCRIPTION
**Pull request by stack72**
- Add support for yaml based provider schemas
- Adding the Java SDK for AWS Api Gateway

# Description

Fixes # (issue)

## Checklist

- [ ] I have added tests that prove my fix is effective or that my feature works

- [ ] I have updated the [CHANGELOG-PENDING](https://github.com/pulumi/pulumi/blob/master/CHANGELOG_PENDING.md) file with my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Service API version

### CODE REVIEW

**Comment by t0yv0** [comment]
Looks good! There's a bit more boilerplaty locations to mention the new provider in:

```
anton@Antons-MacBook-Pro> git grep kubernetes | grep -v '^providers' | grep -v '^pkg/codegen' | grep -v '^tests' | grep -v '^maven' | grep -v '^sdk'                                                           ~/pulumi-java
.github/workflows/cleanup-prerelease-builds.yml:        - kubernetes
.github/workflows/pr.yml:      - kubernetes/v*.*.*
.github/workflows/pr.yml:        - kubernetes
.github/workflows/release-providers-to-maven-central.yml:      - kubernetes/v*.*.*
.github/workflows/release-providers-to-maven-central.yml:        - kubernetes
```

**Review by t0yv0 — APPROVED** [review]

**Comment by pawelprazak** [comment]
I've added it already:
https://github.com/pulumi/pulumi-java/pull/579

**Comment by pawelprazak** [comment]
Mine has slightly better error handling and fixes missed spots after bumping provider versions.

It also builds the provider in the second stage, since it depends on aws.

**Comment by pawelprazak** [comment]
In the future, please look at the issue if it's assigned to anyone before duplicating work: https://github.com/pulumi/pulumi-java/issues/564

**Review by pawelprazak — CHANGES_REQUESTED** [review]
In order to make it built, I believe you need to move the provider build into the second stage of providers, since it depends on aws.

Also I'd wrap the errors in the schama reading.

Also this PR is a duplicate of https://github.com/pulumi/pulumi-java/pull/579
In the future, please look at the issue if it's assigned to anyone before duplicating work: https://github.com/pulumi/pulumi-java/issues/564

**Pull request closed without merging**
