### PR TITLE
Add doc comments to overloads of function invokes

### PR DESCRIPTION
**Pull request by Zaid-Ajaj**
# Description

Not all overloads of function invokes generate the doc comments, this PR fixes that

## Checklist

- [ ] I have added tests that prove my fix is effective or that my feature works

- [x] I have updated the [CHANGELOG-PENDING](https://github.com/pulumi/pulumi/blob/master/CHANGELOG_PENDING.md) file with my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Service API version

### CODE REVIEW

**Comment by dixler** [comment]
did you
```sh
$ PULUMI_ACCEPT=true make codegen_tests
```

**Comment by Zaid-Ajaj** [comment]
> did you `$ PULUMI_ACCEPT=true make codegen_tests`

 @dixler I have now! Fixed the issue and it should be good to go

**Comment by pawelprazak** [comment]
According to the CI, the providers' codegen output has changed but was not versioned.

**Review by t0yv0 — APPROVED** [review]
Thank you!

**Pull request merged**
