### PR TITLE
SBT support

### PR DESCRIPTION
**Pull request by t0yv0**
# Description

This is https://github.com/pulumi/pulumi-java/pull/729 plus a few tiny fixes to make sure CI runs the tests.

Fixes # (issue)

## Checklist

- [ ] I have added tests that prove my fix is effective or that my feature works

- [ ] I have updated the [CHANGELOG-PENDING](https://github.com/pulumi/pulumi/blob/master/CHANGELOG_PENDING.md) file with my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Service API version

### CODE REVIEW

**Review by pawelprazak — APPROVED** [review]
LGTM

**Comment by sideeffffect** [comment]
:tada: :heart:

**Comment by sideeffffect** [comment]
Can we expect a new release containing this fix anytime soon?

**Comment by pawelprazak** [comment]
should be in v0.5.4 that was just released

**Comment by t0yv0** [comment]
So pulumi-language-java 0.5.4 is released, but it will be the "default" in Pulumi only on the next major Pulumi release. We just had one and there is a 2-week cadence. You'd need to grab this release by hand and put it in PATH to use it before the next Pulumi major rel.

**Comment by sideeffffect** [comment]
Btw what would be a good example to test the `com.pulumi.bootstrap.internal.Main packages` functionality on?

**Comment by pawelprazak** [comment]
`com.pulumi.bootstrap.internal.Main` is used by the language host to determine what pulumi plugins need to be downloaded on the CLI side.

**Comment by sideeffffect** [comment]
I see. And is there an easy way how can I (or somebody more experienced with Pulumi) verify that it works for with the recently added Scala/sbt?

**Comment by pawelprazak** [comment]
In general, if you add a pulumi provider dependency, e.g. the random provider, and the language host does not complain and the example works correctly, then it works.

There is also an undocumented internal feature.

If you modify the `tests/examples/random/Pulumi.yaml` to look like this:
```
name: random
description: An example of using pulumi-random with Java
runtime:
  name: java
  options:
    logtostderr: true
    v: 5
```
then the `options` part gets passed to the `pulumi-language-java` binary and after running `pulumi up` you can see that the functionality is working as expected:
```
Diagnostics:
  pulumi:pulumi:Stack (random-java-random):
    I0817 14:54:46.116815   94080 main.go:138] GetRequiredPlugins: program=.
    I0817 14:54:46.116843   94080 main.go:176] GetRequiredPlugins: Determining Pulumi plugins
    I0817 14:54:46.116854   94080 main.go:211] Language host launching process:  /usr/local/bin/mvn -Dorg.slf4j.simpleLogger.logFile=System.err --no-transfer-progress compile exec:java -DmainClass=com.pulumi.bootstrap.internal.Main -DmainArgs=packages
    I0817 14:54:47.938012   94080 main.go:240] '/usr/local/bin/mvn -Dorg.slf4j.simpleLogger.logFile=System.err --no-transfer-progress compile exec:java -DmainClass=com.pulumi.bootstrap.internal.Main -DmainArgs=packages' completed successfully
    I0817 14:54:47.938051   94080 main.go:189] GetRequiredPlugins: bootstrap raw output=[{"resource":true,"name":"random","version":"4.6.0"}]
    I0817 14:54:47.938147   94080 main.go:151] GetRequiredPlugins: Determining plugin dependency: random, 4.6.0
    I0817 14:54:47.938157   94080 main.go:168] GetRequiredPlugins: plugins=[name:"random" kind:"resource" version:"4.6.0"]
    I0817 14:54:48.001341   94080 main.go:248] Run: program=.
    I0817 14:54:48.001356   94080 main.go:267] Language host launching process:  /usr/local/bin/mvn --no-transfer-progress compile exec:java
```
here is the raw JSON output from the `com.pulumi.bootstrap.internal.Main`:
```
GetRequiredPlugins: bootstrap raw output=[{"resource":true,"name":"random","version":"4.6.0"}]
```

**Comment by PhilAndrew** [comment]
Does it work? how to get it to work?

```
t>pulumi up
Please choose a stack, or create a new one: zioplay2
Previewing update (zioplay2)

View Live: https://app.pulumi.com/PhilAndrew/minimalsbt/zioplay2/previews/fc292e91-4d28-490c-9a03-8dc76316a297

     Type                 Name                 Plan     Info
     pulumi:pulumi:Stack  minimalsbt-zioplay2           2 messages

Diagnostics:
  pulumi:pulumi:Stack (minimalsbt-zioplay2):
    I0820 17:56:13.120697    9548 main.go:150] GetRequiredPlugins: program=.
    I0820 17:56:13.120697    9548 main.go:188] GetRequiredPlugins: Determining Pulumi plugins

error: failed to discover plugin requirements: language host could not determine Pulumi packages: Failed to configure executor, tried: jar, maven, gradle, jbang

>pulumi version
v3.38.0

>
```

**Comment by sideeffffect** [comment]
@PhilAndrew 
> tried: jar, maven, gradle, jbang

You're almost surely not using the newest version of `pulumi-java` -- the current version of Pulumi doesn't have the newest pulumi-java, see https://github.com/pulumi/pulumi-java/pull/791#issuecomment-1213197671

**Pull request merged**
