### PR TITLE
go: opt-into gofumpt, reformat

### PR DESCRIPTION
**Pull request by abhinav**
As with pu/pu (https://github.com/pulumi/pulumi/pull/12347),
reformats all Go code with gofumpt and opts the repository into it.

### CODE REVIEW

**Comment by abhinav** [comment]
Current dependencies on/for this PR:
* main
  * **PR #1014** <a href="https://app.graphite.dev/github/pr/pulumi/pulumi-java/1014" target="_blank">Graphite</a> 
    * **PR #1015** <a href="https://app.graphite.dev/github/pr/pulumi/pulumi-java/1015" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/pulumi/pulumi-java/1015?utm_source=stack-comment).

**Review by Frassle — APPROVED** [review]

**Comment by abhinav** [comment]
@abhinav queued this pull request to merge with [Graphite](https://app.graphite.dev/github/pr/pulumi/pulumi-java/1015).

**Comment by abhinav** [comment]
[Graphite](https://app.graphite.dev/github/pr/pulumi/pulumi-java/1015) couldn't merge this pull request because a downstack PR #1014 failed to merge.

**Comment by abhinav** [comment]
@abhinav queued this pull request to merge with [Graphite](https://app.graphite.dev/github/pr/pulumi/pulumi-java/1015).

**Comment by abhinav** [comment]
@abhinav merged this pull request with [Graphite](https://app.graphite.dev/github/pr/pulumi/pulumi-java/1015).

**Pull request merged**
